// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  // Platform'a özgü Firebase yapılandırmasını döndürür
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtuONIOm_BwXfxQF9SSL93Uq-VpnPMLAY',
    appId: '1:241794820589:web:d74ef1054ac2e4f7b55fe4',
    messagingSenderId: '241794820589',
    projectId: 'mobilproje-c0dc4',
    authDomain: 'mobilproje-c0dc4.firebaseapp.com',
    storageBucket: 'mobilproje-c0dc4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxMr1yzWU7uCIvZVA5XA0S7oH_jLOlXD0',
    appId: '1:241794820589:android:1917ce8cf9ccb261b55fe4',
    messagingSenderId: '241794820589',
    projectId: 'mobilproje-c0dc4',
    storageBucket: 'mobilproje-c0dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7jqwxqC4gPFFiuGh1SYXtiKojytO2zAM',
    appId: '1:241794820589:ios:ca6e7c05f9a497beb55fe4',
    messagingSenderId: '241794820589',
    projectId: 'mobilproje-c0dc4',
    storageBucket: 'mobilproje-c0dc4.firebasestorage.app',
    iosBundleId: 'com.example.projedeneme1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7jqwxqC4gPFFiuGh1SYXtiKojytO2zAM',
    appId: '1:241794820589:ios:ca6e7c05f9a497beb55fe4',
    messagingSenderId: '241794820589',
    projectId: 'mobilproje-c0dc4',
    storageBucket: 'mobilproje-c0dc4.firebasestorage.app',
    iosBundleId: 'com.example.projedeneme1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtuONIOm_BwXfxQF9SSL93Uq-VpnPMLAY',
    appId: '1:241794820589:web:741134121899e064b55fe4',
    messagingSenderId: '241794820589',
    projectId: 'mobilproje-c0dc4',
    authDomain: 'mobilproje-c0dc4.firebaseapp.com',
    storageBucket: 'mobilproje-c0dc4.firebasestorage.app',
  );
}
